CREATE TABLE EMPLOYEES
   (EMPLOYEE_ID NUMERIC,
	FIRST_NAME VARCHAR2(20 BYTE),
	LAST_NAME VARCHAR2(25 BYTE) CONSTRAINT EMP_LAST_NAME_NN NOT NULL ENABLE,
	EMAIL VARCHAR2(100 BYTE) CONSTRAINT EMP_EMAIL_NN NOT NULL ENABLE,
	PHONE_NUMBER VARCHAR2(20 BYTE),
	HIRE_DATE DATE CONSTRAINT EMP_HIRE_DATE_NN NOT NULL ENABLE,
	JOB_ID VARCHAR2(10 BYTE) CONSTRAINT EMP_JOB_NN NOT NULL ENABLE,
	SALARY NUMBER(20,2),
	COMMISSION_PCT NUMBER(20,2),
	MANAGER_ID NUMERIC,
	DEPARTMENT_ID NUMERIC,
	 CONSTRAINT EMP_SALARY_MIN CHECK (salary > 0) ENABLE,
	 CONSTRAINT EMP_EMAIL_UK UNIQUE (EMAIL));