create or replace TYPE EMPLOYEE_ROW_TYPE AS OBJECT
(
    COMMISSION_PCT NUMBER(20,2),
    DEPARTMENT_ID NUMERIC,
    EMPLOYEE_ID NUMERIC,
    FIRST_NAME VARCHAR2(20 BYTE),
    HIRE_DATE DATE,
    JOB_ID VARCHAR2(10 BYTE),
    LAST_NAME VARCHAR2(25 BYTE),
    MANAGER_ID NUMERIC,
    PHONE_NUMBER VARCHAR2(20 BYTE),
    SALARY NUMBER(20,2),
    EMAIL VARCHAR2(100 BYTE)
);